name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Vérifier le code
      uses: actions/checkout@v2

    - name: Configurer Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.5'  # Spécifiez la version de Python que vous souhaitez utiliser

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assurez-vous d'avoir un fichier requirements.txt

    - name: Exécuter les tests
      run: |
        pytest  # Exécutez vos tests avec pytest
